services:
  - type: web
    name: kpi-zagonel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GITHUB_TOKEN
        sync: false
